sudo: false

language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"

env:
  - PYTHON=2.7 PANDAS=0.19.2 COVERAGE='false' LINT='true'
  - PYTHON=3.5 PANDAS=0.18.1 COVERAGE='true' LINT='false'
  - PYTHON=3.6 PANDAS=0.20.1 COVERAGE='false' LINT='false'
  - PYTHON=3.6 PANDAS=MASTER COVERAGE='false' LINT='true'

before_install:
  - echo "before_install"
  - source ci/travis_process_gbq_encryption.sh

install:
  - REQ="ci/requirements-${PYTHON}-${PANDAS}" ;
    if [ -f "$REQ.pip" ]; then
      pip install --upgrade nox-automation ;
    else
      wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      bash miniconda.sh -b -p $HOME/miniconda ;
      export PATH="$HOME/miniconda/bin:$PATH" ;
      hash -r ;
      conda config --set always_yes yes --set changeps1 no ;
      conda config --add channels pandas ;
      conda config --add channels conda-forge ;
      conda update -q conda ;
      conda info -a ;
      conda create -q -n test-environment python=$PYTHON ;
      source activate test-environment ;
      conda install -q pandas=$PANDAS;
      pip install coverage pytest pytest-cov flake8 codecov ;
      conda install -q --file "$REQ.conda";
      conda list ;
      python setup.py install ;
    fi

script:
  - if [[ $PYTHON == '2.7' ]]; then nox -s test27 ; fi
  - if [[ $PYTHON == '3.5' ]]; then nox -s test35 ; fi
  - if [[ $PYTHON == '3.6' ]] && [[ "$PANDAS" == "MASTER" ]]; then nox -s test36master ; fi
  - REQ="ci/requirements-${PYTHON}-${PANDAS}" ;
    if [ -f "$REQ.conda" ]; then
      pip install coverage pytest pytest-cov codecov ;
      pytest -v --cov=pandas_gbq --cov-report xml:/tmp/pytest-cov.xml pandas_gbq ;
    fi
  - if [[ $COVERAGE == 'true' ]]; then nox -s cover ; fi
  - if [[ $LINT == 'true' ]]; then nox -s lint ; fi
